// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditRecord struct {
	ID           string             `json:"id"`
	ProjectID    string             `json:"project_id"`
	ActorID      string             `json:"actor_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	CommandID    *string            `json:"command_id"`
	Outcome      string             `json:"outcome"`
	RemoteAddr   *string            `json:"remote_addr"`
	Details      []byte             `json:"details"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
}

type BriefAcknowledgement struct {
	ProjectID      string             `json:"project_id"`
	ActorID        string             `json:"actor_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	CommandID      string             `json:"command_id"`
	ExpectedCursor int64              `json:"expected_cursor"`
	ThroughCursor  int64              `json:"through_cursor"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
}

type BriefCursor struct {
	ProjectID  string             `json:"project_id"`
	ActorID    string             `json:"actor_id"`
	LastCursor int64              `json:"last_cursor"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CommandResult struct {
	ProjectID      string             `json:"project_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Fingerprint    []byte             `json:"fingerprint"`
	CommandID      string             `json:"command_id"`
	Resource       []byte             `json:"resource"`
	Event          []byte             `json:"event"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
}

type Event struct {
	Cursor         int64              `json:"cursor"`
	ID             string             `json:"id"`
	ProjectID      string             `json:"project_id"`
	EventType      string             `json:"event_type"`
	SubjectType    string             `json:"subject_type"`
	SubjectID      string             `json:"subject_id"`
	ActorID        string             `json:"actor_id"`
	CommandID      *string            `json:"command_id"`
	CorrelationID  *string            `json:"correlation_id"`
	CausationID    *string            `json:"causation_id"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	SchemaVersion  int32              `json:"schema_version"`
	SourceSystem   *string            `json:"source_system"`
	SourceEventID  *string            `json:"source_event_id"`
	SourceSequence *int64             `json:"source_sequence"`
	Payload        []byte             `json:"payload"`
}

type EventOutbox struct {
	EventID     string             `json:"event_id"`
	Cursor      int64              `json:"cursor"`
	ProjectID   string             `json:"project_id"`
	Event       []byte             `json:"event"`
	Attempts    int32              `json:"attempts"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type OidcState struct {
	StateHash          []byte             `json:"state_hash"`
	BrowserHash        []byte             `json:"browser_hash"`
	NonceHash          []byte             `json:"nonce_hash"`
	VerifierHash       []byte             `json:"verifier_hash"`
	VerifierCiphertext []byte             `json:"verifier_ciphertext"`
	ReturnTo           string             `json:"return_to"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

type Project struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectMembership struct {
	ProjectID    string             `json:"project_id"`
	UserID       string             `json:"user_id"`
	Capabilities []string           `json:"capabilities"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Resource struct {
	ProjectID      string             `json:"project_id"`
	Kind           string             `json:"kind"`
	ID             string             `json:"id"`
	Version        int64              `json:"version"`
	Document       []byte             `json:"document"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SourceSystem   *string            `json:"source_system"`
	SourceSequence *int64             `json:"source_sequence"`
}

type RunControlOutbox struct {
	ID          string             `json:"id"`
	ProjectID   string             `json:"project_id"`
	RunID       string             `json:"run_id"`
	ActorID     string             `json:"actor_id"`
	CommandID   string             `json:"command_id"`
	Action      string             `json:"action"`
	Message     string             `json:"message"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	LastError   *string            `json:"last_error"`
}

type SchemaMigration struct {
	Version   int64              `json:"version"`
	Name      string             `json:"name"`
	Digest    string             `json:"digest"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type ServiceToken struct {
	TokenHash    []byte             `json:"token_hash"`
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	ActorID      string             `json:"actor_id"`
	ProjectIds   []string           `json:"project_ids"`
	Capabilities []string           `json:"capabilities"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserAccount struct {
	ID           string             `json:"id"`
	Username     string             `json:"username"`
	PasswordHash *string            `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	Disabled     bool               `json:"disabled"`
	Capabilities []string           `json:"capabilities"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WebSession struct {
	TokenHash   []byte             `json:"token_hash"`
	UserID      string             `json:"user_id"`
	CsrfHash    []byte             `json:"csrf_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	OidcSubject *string            `json:"oidc_subject"`
}
