// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	GetProjectCapabilities(ctx context.Context, arg GetProjectCapabilitiesParams) ([]string, error)
	GetResource(ctx context.Context, arg GetResourceParams) ([]byte, error)
	GetServiceToken(ctx context.Context, tokenHash []byte) (GetServiceTokenRow, error)
	LatestProjectEventCursor(ctx context.Context, projectID string) (int64, error)
	ResourceHealth(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
