// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: resources.sql

package sqlcgen

import (
	"context"
)

const getProjectCapabilities = `-- name: GetProjectCapabilities :one
SELECT capabilities
FROM project_memberships
WHERE project_id = $1 AND user_id = $2
`

type GetProjectCapabilitiesParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetProjectCapabilities(ctx context.Context, arg GetProjectCapabilitiesParams) ([]string, error) {
	row := q.db.QueryRow(ctx, getProjectCapabilities, arg.ProjectID, arg.UserID)
	var capabilities []string
	err := row.Scan(&capabilities)
	return capabilities, err
}

const getResource = `-- name: GetResource :one
SELECT document
FROM resources
WHERE project_id = $1 AND kind = $2 AND id = $3
`

type GetResourceParams struct {
	ProjectID string `json:"project_id"`
	Kind      string `json:"kind"`
	ID        string `json:"id"`
}

func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getResource, arg.ProjectID, arg.Kind, arg.ID)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const getServiceToken = `-- name: GetServiceToken :one
SELECT id, actor_id, project_ids, capabilities
FROM service_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

type GetServiceTokenRow struct {
	ID           string   `json:"id"`
	ActorID      string   `json:"actor_id"`
	ProjectIds   []string `json:"project_ids"`
	Capabilities []string `json:"capabilities"`
}

func (q *Queries) GetServiceToken(ctx context.Context, tokenHash []byte) (GetServiceTokenRow, error) {
	row := q.db.QueryRow(ctx, getServiceToken, tokenHash)
	var i GetServiceTokenRow
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.ProjectIds,
		&i.Capabilities,
	)
	return i, err
}

const latestProjectEventCursor = `-- name: LatestProjectEventCursor :one
SELECT COALESCE(max(cursor), 0)::bigint
FROM events
WHERE project_id = $1
`

func (q *Queries) LatestProjectEventCursor(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, latestProjectEventCursor, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const resourceHealth = `-- name: ResourceHealth :one
SELECT 1::bigint
`

func (q *Queries) ResourceHealth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, resourceHealth)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
